version: '2'
services:
    resttest-app:
        image: resttest
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://resttest-mysql:3306/resttest?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    resttest-mysql:
        extends:
            file: mysql.yml
            service: resttest-mysql
